export const movements = [
  {
    id: 1,
    account_id: 1,
    year: 2022,
    month: 10,
    day: 2,
    price: 54.2,
    libellé: "marché bio",
    crédit: false,
    débit: true,
    fixed: true,
  },
  {
    id: 2,
    account_id: 1,
    year: 2022,
    month: 10,
    day: 2,
    price: 5,
    libellé: "pourboire",
    crédit: false,
    débit: true,
    fixed: true,
  },
  {
    id: 3,
    account_id: 1,
    year: 2022,
    month: 10,
    day: 3,
    price: 72.3,
    libellé: "remboursement la redoute",
    crédit: true,
    débit: false,
    fixed: false,
  },
  {
    id: 4,
    account_id: 1,
    year: 2023,
    month: 1,
    day: 3,
    price: 7.4,
    libellé: "boulangerie",
    crédit: false,
    débit: true,
    fixed: false,
  },
  {
    id: 5,
    account_id: 1,
    year: 2022,
    month: 11,
    day: 18,
    price: 41,
    libellé: "musée art",
    crédit: false,
    débit: true,
    fixed: false,
  },
  {
    id: 6,
    account_id: 1,
    year: 2022,
    month: 12,
    day: 18,
    price: 41,
    libellé: "musée art",
    crédit: false,
    débit: true,
    fixed: false,
  },
];
